"""add color in table class

Revision ID: 004f3a347994
Revises: 
Create Date: 2022-11-07 16:06:57.588402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004f3a347994'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('color', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class', 'color')
    # ### end Alembic commands ###
