"""change task_date and task_time to be nullable

Revision ID: 2055d3c84ada
Revises: e35e96018064
Create Date: 2022-10-22 17:31:18.680101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2055d3c84ada'
down_revision = 'e35e96018064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'task_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('task', 'task_time',
               existing_type=mysql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'task_time',
               existing_type=mysql.TIME(),
               nullable=False)
    op.alter_column('task', 'task_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
