"""add completed_date in table task

Revision ID: 2f52f4ff532d
Revises: dc21e0314464
Create Date: 2022-11-10 16:00:20.437582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f52f4ff532d'
down_revision = 'dc21e0314464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'completed_date')
    # ### end Alembic commands ###
