"""add completed_time in table task

Revision ID: 6622f9f87fd3
Revises: 2f52f4ff532d
Create Date: 2022-11-11 14:08:41.083840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6622f9f87fd3'
down_revision = '2f52f4ff532d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'completed_time')
    # ### end Alembic commands ###
