"""add task_date

Revision ID: 8736e0ff55c7
Revises: 004f3a347994
Create Date: 2022-11-07 16:07:23.081438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8736e0ff55c7'
down_revision = '004f3a347994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_date', sa.Date(), nullable=True))
    op.add_column('task', sa.Column('task_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'task_time')
    op.drop_column('task', 'task_date')
    # ### end Alembic commands ###
