"""create the table task

Revision ID: a2d39eda033a
Revises: ec6231a2203a
Create Date: 2022-10-22 13:37:56.291997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d39eda033a'
down_revision = 'ec6231a2203a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('tid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('task_description', sa.String(length=1000), nullable=False),
    sa.Column('task_status', sa.Boolean(), nullable=False),
    sa.Column('task_date', sa.Date(), nullable=False),
    sa.Column('task_time', sa.Time(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.cid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('tid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
