"""add column uc_id in task

Revision ID: bd8e361a1d3b
Revises: 
Create Date: 2022-11-04 14:59:16.007584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8e361a1d3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('uc_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'user_class', ['uc_id'], ['uc_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'uc_id')
    # ### end Alembic commands ###
