"""add informed in table task

Revision ID: dc21e0314464
Revises: 8736e0ff55c7
Create Date: 2022-11-07 16:07:45.817299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc21e0314464'
down_revision = '8736e0ff55c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('informed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'informed')
    # ### end Alembic commands ###
