"""add the column usermail to the table user

Revision ID: ea5e90d1c285
Revises: a2d39eda033a
Create Date: 2022-10-22 13:44:54.388176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea5e90d1c285'
down_revision = 'a2d39eda033a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usermail', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'usermail')
    # ### end Alembic commands ###
