"""add usermail, cname, color unique

Revision ID: f729c8e91eac
Revises: ea5e90d1c285
Create Date: 2022-10-22 15:43:31.615527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f729c8e91eac'
down_revision = 'ea5e90d1c285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'class', ['color'])
    op.create_unique_constraint(None, 'class', ['cname'])
    op.create_unique_constraint(None, 'user', ['usermail'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'class', type_='unique')
    op.drop_constraint(None, 'class', type_='unique')
    # ### end Alembic commands ###
